import type { NextApiRequest, NextApiResponse } from "next";
import { verifyApiKey } from "@/lib/console-utils";

const MODELS = [
  {
    id: "google/gemini-3-flash-preview",
    object: "model",
    created: 1748000000,
    owned_by: "google",
    description: "Google Gemini 3 Flash — fast and efficient multimodal model",
    context_window: 1000000,
    capabilities: ["chat", "multimodal", "streaming"],
    tier: "free",
  },
  {
    id: "openai/gpt-5-mini",
    object: "model",
    created: 1748100000,
    owned_by: "openai",
    description: "OpenAI GPT-5 Mini — lightweight and fast text model",
    context_window: 128000,
    capabilities: ["chat", "streaming"],
    tier: "free",
  },
  {
    id: "openai/gpt-5.2",
    object: "model",
    created: 1748200000,
    owned_by: "openai",
    description: "OpenAI GPT-5.2 — advanced reasoning and instruction following",
    context_window: 128000,
    capabilities: ["chat", "streaming"],
    tier: "pro",
  },
  {
    id: "openai/gpt-5.5",
    object: "model",
    created: 1748220000,
    owned_by: "openai",
    description: "OpenAI GPT-5.5 — next-generation flagship reasoning model",
    context_window: 128000,
    capabilities: ["chat"],
    tier: "pro",
  },
  {
    id: "openai/gpt-oss-120b",
    object: "model",
    created: 1747500000,
    owned_by: "openai",
    description: "OpenAI OSS 120B — open-source large language model",
    context_window: 128000,
    capabilities: ["chat", "streaming"],
    tier: "free",
  },
  {
    id: "anthropic/claude-sonnet-4-6",
    object: "model",
    created: 1748280000,
    owned_by: "anthropic",
    description: "Anthropic Claude Sonnet 4.6 — balanced reasoning and speed",
    context_window: 200000,
    capabilities: ["chat", "streaming"],
    tier: "pro",
  },
  {
    id: "anthropic/claude-opus-4-8",
    object: "model",
    created: 1748300000,
    owned_by: "anthropic",
    description: "Anthropic Claude Opus 4.8 — powerful reasoning and analysis",
    context_window: 200000,
    capabilities: ["chat", "multimodal"],
    tier: "enterprise",
  },
  {
    id: "anthropic/claude-haiku-4-5",
    object: "model",
    created: 1748260000,
    owned_by: "anthropic",
    description: "Anthropic Claude Haiku 4.5 — fast and lightweight model",
    context_window: 200000,
    capabilities: ["chat"],
    tier: "free",
  },
  {
    id: "anthropic/claude-fable-5",
    object: "model",
    created: 1748330000,
    owned_by: "anthropic",
    description: "Anthropic Claude Fable 5 — Mythos-tier creative reasoning model",
    context_window: 200000,
    capabilities: ["chat", "streaming"],
    tier: "enterprise",
  },
  {
    id: "deepseek/deepseek-v4-pro",
    object: "model",
    created: 1748400000,
    owned_by: "deepseek",
    description: "DeepSeek V4 Pro — high performance open-source model",
    context_window: 128000,
    capabilities: ["chat", "streaming"],
    tier: "pro",
  },
  {
    id: "deepseek/deepseek-v4-flash",
    object: "model",
    created: 1748420000,
    owned_by: "deepseek",
    description: "DeepSeek V4 Flash — fast lightweight DeepSeek model",
    context_window: 128000,
    capabilities: ["chat", "streaming"],
    tier: "free",
  },
  {
    id: "moonshotai/kimi-k2.6",
    object: "model",
    created: 1748500000,
    owned_by: "moonshotai",
    description: "Moonshot Kimi K2.6 — long context and reasoning model",
    context_window: 128000,
    capabilities: ["chat", "streaming"],
    tier: "pro",
  },
  {
    id: "z-ai/glm-5.2",
    object: "model",
    created: 1748150000,
    owned_by: "z-ai",
    description: "Zhipu GLM-5.2 — bilingual Chinese-English model",
    context_window: 128000,
    capabilities: ["chat", "streaming"],
    tier: "pro",
  },
  {
    id: "z-ai/glm-4.7-flash",
    object: "model",
    created: 1748160000,
    owned_by: "z-ai",
    description: "Zhipu GLM-4.7 Flash — fast bilingual model",
    context_window: 128000,
    capabilities: ["chat", "streaming"],
    tier: "free",
  },
  {
    id: "mistralai/mistral-large-latest",
    object: "model",
    created: 1747600000,
    owned_by: "mistralai",
    description: "Mistral Large — efficient European flagship model",
    context_window: 128000,
    capabilities: ["chat", "streaming"],
    tier: "free",
  },
  {
    id: "alibaba/qwen3.8-27b",
    object: "model",
    created: 1748250000,
    owned_by: "alibaba",
    description: "Alibaba Qwen3.8 27B — multilingual instruction model",
    context_window: 128000,
    capabilities: ["chat", "streaming"],
    tier: "free",
  },
  {
    id: "alibaba/qwen3-coder-plus",
    object: "model",
    created: 1748350000,
    owned_by: "alibaba",
    description: "Alibaba Qwen3 Coder Plus — specialized coding model",
    context_window: 128000,
    capabilities: ["chat", "code", "streaming"],
    tier: "free",
  },
  {
    id: "minimaxai/minimax-m3",
    object: "model",
    created: 1748050000,
    owned_by: "minimaxai",
    description: "MiniMax M3 — multimodal and long context model",
    context_window: 1000000,
    capabilities: ["chat", "multimodal", "streaming"],
    tier: "pro",
  },
  {
    id: "meta/llama-3.3-70b",
    object: "model",
    created: 1747400000,
    owned_by: "meta",
    description: "Meta Llama 3.3 70B — open-source instruction model",
    context_window: 128000,
    capabilities: ["chat", "streaming"],
    tier: "free",
  },
  {
    id: "meta/llama-4-scout-17b-16e-instruct",
    object: "model",
    created: 1747420000,
    owned_by: "meta",
    description: "Meta Llama 4 Scout — multimodal vision-capable model",
    context_window: 128000,
    capabilities: ["chat", "multimodal", "streaming"],
    tier: "free",
  },
  {
    id: "xiaomi/mimo-v2.5-pro",
    object: "model",
    created: 1748450000,
    owned_by: "xiaomi",
    description: "Xiaomi MiMo V2.5 Pro — fast lightweight model",
    context_window: 32000,
    capabilities: ["chat", "streaming"],
    tier: "pro",
  },
  {
    id: "microsoft/phi-4-multimodal-instruct",
    object: "model",
    created: 1747950000,
    owned_by: "microsoft",
    description: "Microsoft Phi-4 Multimodal — compact multimodal instruction model",
    context_window: 128000,
    capabilities: ["chat", "multimodal"],
    tier: "free",
  },
  {
    id: "groq/compound",
    object: "model",
    created: 1747700000,
    owned_by: "groq",
    description: "Groq Compound — compound AI system with tool use",
    context_window: 128000,
    capabilities: ["chat", "tools", "streaming"],
    tier: "free",
  },
  {
    id: "cohere/command-a",
    object: "model",
    created: 1747900000,
    owned_by: "cohere",
    description: "Cohere Command A — enterprise-grade language model",
    context_window: 256000,
    capabilities: ["chat", "streaming"],
    tier: "free",
  },
  {
    id: "xai/grok-3",
    object: "model",
    created: 1748550000,
    owned_by: "xai",
    description: "xAI Grok 3 — real-time knowledge and reasoning",
    context_window: 131072,
    capabilities: ["chat"],
    tier: "free",
  },
  {
    id: "xai/grok-4-fast",
    object: "model",
    created: 1748600000,
    owned_by: "xai",
    description: "xAI Grok 4 Fast — latest Grok with enhanced speed",
    context_window: 131072,
    capabilities: ["chat"],
    tier: "pro",
  },
  {
    id: "stepfun-ai/step-3.7-flash",
    object: "model",
    created: 1748620000,
    owned_by: "stepfun-ai",
    description: "StepFun Step 3.7 Flash — fast reasoning model",
    context_window: 128000,
    capabilities: ["chat", "streaming"],
    tier: "free",
  },
  {
    id: "nvidia/nemotron-3-ultra-550b-a55b",
    object: "model",
    created: 1748640000,
    owned_by: "nvidia",
    description: "NVIDIA Nemotron 3 Ultra — large mixture-of-experts model",
    context_window: 128000,
    capabilities: ["chat", "streaming"],
    tier: "pro",
  },
  {
    id: "poolside/laguna-s-2.1",
    object: "model",
    created: 1748660000,
    owned_by: "poolside",
    description: "Poolside Laguna S 2.1 — coding and reasoning model",
    context_window: 128000,
    capabilities: ["chat", "streaming"],
    tier: "pro",
  },
  {
    id: "thinkingmachines/inkling",
    object: "model",
    created: 1748680000,
    owned_by: "thinkingmachines",
    description: "Thinking Machines Inkling — experimental reasoning model",
    context_window: 128000,
    capabilities: ["chat", "multimodal", "streaming"],
    tier: "pro",
  },
  {
    id: "google/gemma-4-31b",
    object: "model",
    created: 1748700000,
    owned_by: "google",
    description: "Google Gemma 4 31B — open-weight efficient model",
    context_window: 128000,
    capabilities: ["chat", "streaming"],
    tier: "free",
  },
  {
    id: "aichixia/aichixia-flash",
    object: "model",
    created: 1748650000,
    owned_by: "aichixia",
    description: "Aichixia Flash — proprietary fast reasoning model",
    context_window: 200000,
    capabilities: ["chat", "reasoning", "streaming"],
    tier: "pro",
  },
  {
    id: "flux",
    object: "model",
    created: 1698785189,
    owned_by: "black-forest-labs",
    description: "FLUX.1 — state-of-the-art text-to-image generation",
    capabilities: ["image-generation"],
    tier: "free",
  },
  {
    id: "lucid",
    object: "model",
    created: 1699000000,
    owned_by: "leonardo",
    description: "Lucid — high quality image generation model",
    capabilities: ["image-generation"],
    tier: "free",
  },
  {
    id: "phoenix",
    object: "model",
    created: 1699100000,
    owned_by: "leonardo",
    description: "Phoenix — creative and artistic image generation",
    capabilities: ["image-generation"],
    tier: "free",
  },
  {
    id: "nano banana",
    object: "model",
    created: 1699200000,
    owned_by: "google",
    description: "Nano — fast lightweight image generation",
    capabilities: ["image-generation"],
    tier: "free",
  },
  {
    id: "starling",
    object: "model",
    created: 1699053241,
    owned_by: "aichixia",
    description: "Starling — natural expressive text-to-speech",
    capabilities: ["text-to-speech"],
    tier: "free",
  },
  {
    id: "lindsay",
    object: "model",
    created: 1699300000,
    owned_by: "typecast",
    description: "Lindsay — premium voice synthesis with emotion control",
    capabilities: ["text-to-speech"],
    tier: "free",
  },
];

export default async function handler(req: NextApiRequest, res: NextApiResponse) {
  if (req.method !== "GET") {
    return res.status(405).json({
      error: {
        message: "Method not allowed",
        type: "invalid_request_error",
        param: null,
        code: null,
      },
    });
  }

  const apiKey = req.headers.authorization?.replace("Bearer ", "");

  if (!apiKey) {
    return res.status(401).json({
      error: {
        message: "Missing API key in Authorization header",
        type: "invalid_request_error",
        param: null,
        code: "missing_api_key",
      },
    });
  }

  const verifyResult = await verifyApiKey(apiKey);
  if (!verifyResult || !verifyResult.key) {
    return res.status(401).json({
      error: {
        message: "Invalid API key",
        type: "invalid_request_error",
        param: null,
        code: "invalid_api_key",
      },
    });
  }

  return res.status(200).json({
    object: "list",
    data: MODELS,
  });
}
