import type { NextApiRequest, NextApiResponse } from "next";
import { verifyApiKey } from "@/lib/console-utils";

const MODELS = [
  {
    id: "gemini-3-flash",
    object: "model",
    created: 1748000000,
    owned_by: "google",
    description: "Google Gemini 3 Flash — fast and efficient multimodal model",
    context_window: 1000000,
    capabilities: ["chat", "multimodal"],
    tier: "free",
  },
  {
    id: "gpt-5-mini",
    object: "model",
    created: 1748100000,
    owned_by: "openai",
    description: "OpenAI GPT-5 Mini — lightweight and fast text model",
    context_window: 128000,
    capabilities: ["chat"],
    tier: "free",
  },
  {
    id: "gpt-5.2",
    object: "model",
    created: 1748200000,
    owned_by: "openai",
    description: "OpenAI GPT-5.2 — advanced reasoning and instruction following",
    context_window: 128000,
    capabilities: ["chat"],
    tier: "free",
  },
  {
    id: "gpt-oss-120b",
    object: "model",
    created: 1747500000,
    owned_by: "openai",
    description: "OpenAI OSS 120B — open-source large language model",
    context_window: 128000,
    capabilities: ["chat"],
    tier: "free",
  },
  {
    id: "claude-opus-4.5",
    object: "model",
    created: 1748300000,
    owned_by: "anthropic",
    description: "Anthropic Claude Opus 4.5 — powerful reasoning and analysis",
    context_window: 200000,
    capabilities: ["chat", "multimodal"],
    tier: "pro",
  },
  {
    id: "deepseek-v3.2",
    object: "model",
    created: 1748400000,
    owned_by: "liang wenfeng",
    description: "DeepSeek V3.2 — high performance open-source model",
    context_window: 128000,
    capabilities: ["chat"],
    tier: "pro",
  },
  {
    id: "deepseek-v3.1",
    object: "model",
    created: 1747800000,
    owned_by: "liang wenfeng",
    description: "DeepSeek V3.1 — previous generation DeepSeek model",
    context_window: 128000,
    capabilities: ["chat"],
    tier: "free",
  },
  {
    id: "kimi-k2",
    object: "model",
    created: 1748500000,
    owned_by: "moonshot",
    description: "Moonshot Kimi K2 — long context and reasoning model",
    context_window: 128000,
    capabilities: ["chat"],
    tier: "pro",
  },
  {
    id: "glm-4.7",
    object: "model",
    created: 1748150000,
    owned_by: "zhipu",
    description: "Zhipu GLM-4.7 — bilingual Chinese-English model",
    context_window: 128000,
    capabilities: ["chat"],
    tier: "pro",
  },
  {
    id: "mistral-3.1",
    object: "model",
    created: 1747600000,
    owned_by: "mistral",
    description: "Mistral 3.1 — efficient European open-source model",
    context_window: 128000,
    capabilities: ["chat"],
    tier: "free",
  },
  {
    id: "qwen3-235b",
    object: "model",
    created: 1748250000,
    owned_by: "alibaba",
    description: "Alibaba Qwen3 235B — massive multilingual model",
    context_window: 128000,
    capabilities: ["chat"],
    tier: "pro",
  },
  {
    id: "qwen3-coder-480b",
    object: "model",
    created: 1748350000,
    owned_by: "alibaba",
    description: "Alibaba Qwen3 Coder 480B — specialized coding model",
    context_window: 128000,
    capabilities: ["chat", "code"],
    tier: "free",
  },
  {
    id: "minimax-m2.1",
    object: "model",
    created: 1748050000,
    owned_by: "minimax",
    description: "MiniMax M2.1 — multimodal and long context model",
    context_window: 1000000,
    capabilities: ["chat", "multimodal"],
    tier: "pro",
  },
  {
    id: "llama-3.3-70b",
    object: "model",
    created: 1747400000,
    owned_by: "meta",
    description: "Meta LLaMA 3.3 70B — open-source instruction model",
    context_window: 128000,
    capabilities: ["chat"],
    tier: "free",
  },
  {
    id: "mimo-v2-flash",
    object: "model",
    created: 1748450000,
    owned_by: "xiaomi",
    description: "Mimo V2 Flash — ultra-fast lightweight model",
    context_window: 32000,
    capabilities: ["chat"],
    tier: "free",
  },
  {
    id: "groq-compound",
    object: "model",
    created: 1747700000,
    owned_by: "groq",
    description: "Groq Compound — compound AI system with tool use",
    context_window: 128000,
    capabilities: ["chat", "tools"],
    tier: "free",
  },
  {
    id: "cohere-command-a",
    object: "model",
    created: 1747900000,
    owned_by: "cohere",
    description: "Cohere Command A — enterprise-grade language model",
    context_window: 256000,
    capabilities: ["chat"],
    tier: "free",
  },
  {
    id: "grok-3",
    object: "model",
    created: 1748550000,
    owned_by: "xai",
    description: "xAI Grok 3 — real-time knowledge and reasoning",
    context_window: 131072,
    capabilities: ["chat"],
    tier: "free",
  },
  {
    id: "grok-4-fast",
    object: "model",
    created: 1748600000,
    owned_by: "xai",
    description: "xAI Grok 4 Fast — latest Grok with enhanced speed",
    context_window: 131072,
    capabilities: ["chat"],
    tier: "pro",
  },
  {
    id: "aichixia-thinking",
    object: "model",
    created: 1748650000,
    owned_by: "aichixia",
    description: "Aichixia Thinking — proprietary deep reasoning model",
    context_window: 200000,
    capabilities: ["chat", "reasoning"],
    tier: "pro",
  },
  {
    id: "flux",
    object: "model",
    created: 1698785189,
    owned_by: "black-forest-labs",
    description: "FLUX.1 — state-of-the-art text-to-image generation",
    capabilities: ["image-generation"],
    tier: "free",
  },
  {
    id: "lucid",
    object: "model",
    created: 1699000000,
    owned_by: "leonardo",
    description: "Lucid — high quality image generation model",
    capabilities: ["image-generation"],
    tier: "free",
  },
  {
    id: "phoenix",
    object: "model",
    created: 1699100000,
    owned_by: "leonardo",
    description: "Phoenix — creative and artistic image generation",
    capabilities: ["image-generation"],
    tier: "free",
  },
  {
    id: "nano banana",
    object: "model",
    created: 1699200000,
    owned_by: "google",
    description: "Nano — fast lightweight image generation",
    capabilities: ["image-generation"],
    tier: "free",
  },
  {
    id: "starling",
    object: "model",
    created: 1699053241,
    owned_by: "aichixia",
    description: "Starling — natural expressive text-to-speech",
    capabilities: ["text-to-speech"],
    tier: "free",
  },
  {
    id: "lindsay",
    object: "model",
    created: 1699300000,
    owned_by: "typecast",
    description: "Lindsay — premium voice synthesis with emotion control",
    capabilities: ["text-to-speech"],
    tier: "free",
  },
];

export default async function handler(req: NextApiRequest, res: NextApiResponse) {
  if (req.method !== "GET") {
    return res.status(405).json({
      error: {
        message: "Method not allowed",
        type: "invalid_request_error",
        param: null,
        code: null,
      },
    });
  }

  const apiKey = req.headers.authorization?.replace("Bearer ", "");

  if (!apiKey) {
    return res.status(401).json({
      error: {
        message: "Missing API key in Authorization header",
        type: "invalid_request_error",
        param: null,
        code: "missing_api_key",
      },
    });
  }

  const verifyResult = await verifyApiKey(apiKey);
  if (!verifyResult || !verifyResult.key) {
    return res.status(401).json({
      error: {
        message: "Invalid API key",
        type: "invalid_request_error",
        param: null,
        code: "invalid_api_key",
      },
    });
  }

  return res.status(200).json({
    object: "list",
    data: MODELS,
  });
}
